server:
  port: 9306
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: yidianwuyou2019
    key-alias: tomcat
    enabled: true
http:
  port: 9307
yz:
#  filePath: /usr/local/yzFile/
  filePath: F:/images/